{{- if .Values.vm_dist.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "mongooseim.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "mongooseim.fullname" . }}-vmdist
data:
  vm.dist.args: |-

    -proto_dist inet_tls
    -ssl_dist_opt server_certfile   /usr/lib/mongooseim/priv/ssl/mongooseim.pem client_certfile   /usr/lib/mongooseim/priv/ssl/mongooseim.pem
    server_keyfile    /usr/lib/mongooseim/priv/ssl/iq3root.pem  client_keyfile   /usr/lib/mongooseim/priv/ssl/iq3root.pem
    server_cacertfile /usr/lib/mongooseim/priv/ssl/ca.pem client_cacertfile /usr/lib/mongooseim/priv/ssl/ca.pem

    client_verify     verify_peer
    server_verify     verify_peer
    server_fail_if_no_peer_cert true

{{- end }}
