{{- if .Values.vm_args.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "mongooseim.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "mongooseim.fullname" . }}-vmargs
data:
  vm.args: |-
      ## Name of the node.
      -name mongooseim

      ## Cookie for distributed erlang
      -setcookie ejabberd

      ## Enable more processes (10M)
      +P 10000000

      ## Increase number of concurrent ports/sockets
      -env ERL_MAX_PORTS 250000

      ## Tweak GC to run more often
      -env ERL_FULLSWEEP_AFTER 2

      ## With lager sasl reports are redundant so turn them off
      -sasl sasl_error_logger false

      -kernel inet_dist_listen_min 9200
      -kernel inet_dist_listen_max 9209
{{- end }}
