apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongooseim.serviceName" . }}-lb
  labels:
    {{- include "mongooseim.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 5222
      targetPort: 5222
  selector:
    {{- include "mongooseim.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadBalancerIP }}
