apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongooseim.serviceName" . }}
  labels:
    {{- include "mongooseim.labels" . | nindent 4 }}
spec:
{{/*  type: {{ .Values.service.type }}*/}}
  ports:
    - name: epmd
      port: 4369
      targetPort: 4369
    - name: c2s
      port: 5222
      targetPort: 5222
    - name: s2s
      port: 5269
      targetPort: 5269
    - name: bosh
      port: 5280
      targetPort: 5280
    - name: erl-dist-9200
      targetPort: 9200
      port: 9200
    - name: erl-dist-9201
      targetPort: 9201
      port: 9201
    - name: erl-dist-9202
      targetPort: 9202
      port: 9202
    - name: erl-dist-9203
      targetPort: 9203
      port: 9203
    - name: erl-dist-9204
      targetPort: 9204
      port: 9204
    - name: erl-dist-9205
      targetPort: 9205
      port: 9205
    - name: erl-dist-9206
      targetPort: 9206
      port: 9206
    - name: erl-dist-9207
      targetPort: 9207
      port: 9207
    - name: erl-dist-9208
      targetPort: 9208
      port: 9208
    - name: erl-dist-9209
      targetPort: 9209
      port: 9209


  clusterIP: None
  selector:
    {{- include "mongooseim.selectorLabels" . | nindent 4 }}
