apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphite-exporter.fullname" . }}
  labels:
    {{- include "graphite-exporter.labels" . | nindent 4 }}
spec:
  ports:
  - name: graphite
    port: 9109
    targetPort: 9109
  - name: metrics
    port: 9108
    targetPort: 9108
  clusterIP: None
  selector:
    {{- include "graphite-exporter.selectorLabels" . | nindent 4 }}
